feos-org/feos

- CHANGELOG.md
- feos-core/CHANGELOG.md
- feos-core/src/parameter/mod.rs
- feos-core/src/python/cubic.rs
- feos-core/src/python/parameter.rs
- src/gc_pcsaft/dft/parameter.rs
- src/pcsaft/python.rs
Fixes #28 
- Made binary parameters in `from_records` python routine an `Option`. 
- added panic with message when parsing missing `Identifiers` variants.
> Make `binary_parameters` in `from_records` optional and replace unwrap with panic with message

- src/association/mod.rs
- src/pcsaft/parameters.rs
- src/pcsaft/python.rs
This makes the creation of `PcSaftRecord` compatible between 0.2 and 0.3.
> Hide AssociationRecord in PcSaftRecord::new

- CHANGELOG.md
- docs/api/eos.md
- src/estimator/python.rs
- src/estimator/vapor_pressure.rs
This PR adds a new optional argument to the constructors of `VaporPressure` and `DataSet.vapor_pressure`, i.e. the critical temperature.
- If provided, it is used as initial temperature when calculating the critical point in the `predict` method.
- If not provided, the maximum temperature of the input temperatures is used.
- If the calculation of the critical point within `predict` fails (using either the provided or maximum temperature), another call to the method using the default temperatures is used.
- Did some cleanup of the documentation and added `eos.estimator` to the documentation.
> Add `critical_temperature` argument to `VaporPressure` constructor

- CHANGELOG.md
- src/pcsaft/parameters.rs
This PR excludes additional molecules from the homo GC method when using integer inputs. Previously molecules were allowed that had multiple occurrences of the same polar or associating group or one polar and one associating group. Both of these cases are now disabled, because they extrapolate to fluids for which the combination rules were not designed/validated.
There are still molecules allowed that were not part of the parameter estimation, e.g., secondary and tertiary alcohols and alkenols. In particular for the latter the GC method can be assumed to extrapolate adequately robustly and the combination rules are unproblematic.
> Enforce the limitations of the homo gc method for PC-SAFT more strictly

- Cargo.toml
- benches/README.md
- benches/dual_numbers.rs
- benches/state_creation.rs
- benches/state_properties.rs
- feos-core/CHANGELOG.md
- feos-core/src/equation_of_state.rs
- feos-core/src/python/statehd.rs
- feos-core/src/python/user_defined.rs
- feos-core/src/state/cache.rs
- feos-core/src/state/mod.rs
- feos-core/src/state/properties.rs
- feos-dft/src/functional_contribution.rs
This PR introduces the new variant `PartialDerivative::Second` and renames the existing variant to `PartialDerivative::SecondMixed`. `PartialDerivative::Second` can be used to calculate second order derivatives using `Dual2` instead of `HyperDual`, which is sufficient for non-mixed derivatives and computationally less expensive.
The new `PartialDerivative` looks like so
```rust
#[derive(Clone, Copy, Eq, Hash, PartialEq, Debug)]
pub(crate) enum PartialDerivative {
Zeroth,
First(Derivative),
Second(Derivative),
SecondMixed(Derivative, Derivative),
Third(Derivative),
}
```
We can use this variant to calculate non-mixed second order derivatives like so:
```rust
fn dp_dv_(&self, evaluate: Evaluate) -> QuantityScalar<U> {
-self.get_or_compute_derivative(PartialDerivative::Second(DV), evaluate) …
```
> Add non-mixed second order derivatives to `State` property evaluation

- benches/dual_numbers.rs
- benches/state_creation.rs
In preparation for a comparison of different AD schemes for the calculation of critical points.
> Add benchmarks for binary critical points

- feos-core/CHANGELOG.md
- feos-core/src/equation_of_state.rs
- feos-core/src/phase_equilibria/bubble_dew.rs
- feos-core/src/state/critical_point.rs
- feos-core/src/state/properties.rs
The new automatic differentiation scheme halves the number of model evaluations which leads to a ~20-25% decrease in computation time.
> Use single function evaluation in the calculation of critical points

- Cargo.toml
- benches/README.md
- benches/dft_pore.rs
This moves the DFT benchmark that existed vaguely somewhere in a Notebook into the Rust benchmarks.
> Add DFT benchmark

- benches/state_properties.rs
- docs/theory/eos/properties.md
- docs/tutorials/eos/pcsaft/pcsaft_state.ipynb
- examples/pcsaft_state.ipynb
- feos-core/CHANGELOG.md
- feos-core/src/phase_equilibria/bubble_dew.rs
- feos-core/src/python/state.rs
- feos-core/src/state/properties.rs
- feos-dft/src/adsorption/mod.rs
`molar_volume` should be called `partial_molar_volume` to not be confused with `V/N`.
Also #105 revealed confusion around the `ln_phi_pure` function which should be more accurately called `ln_phi_pure_liquid`
> Rename `molar_volume` and `ln_phi_pure`

- CHANGELOG.md
- feos-core/CHANGELOG.md
- feos-core/src/phase_equilibria/phase_diagram_binary.rs
- feos-core/src/phase_equilibria/phase_diagram_pure.rs
- feos-core/src/phase_equilibria/phase_envelope.rs
- feos-core/src/python/phase_equilibria.rs
- feos-core/src/python/state.rs
- feos-core/src/state/properties.rs
- parameters/pcsaft/README.md
- src/python/dft.rs
- src/python/eos.rs
This allows code like
```python
PhaseDiagram(
[
State(eos, temperature, pressure=p, moles=feed).tp_flash()
for p in pressure
if not State(eos, temperature, pressure=p, moles=feed).is_stable()
]
)
```
From the resulting `PhaseDiagram` object, the properties can then be obtained without having to write loops.
Similar to that `StateVec` is exposed in Python and gets a corresponding constructor, that can be used like this:
```python
StateVec([State(eos, temperature, pressure=p, moles=feed) for p in pressure])
```
Other smaller changes:
- `PhaseDiagram` "inherits" the const generic that indicates the number of phases from `PhaseEquilibrium`. It was a somewhat unnecessary limitation, that could make future additions breaking changes. In Python `PhaseDiagram` is still fixed to 2 phases and there …
> Add custom PhaseDiagram constructor

- CHANGELOG.md
- feos-core/CHANGELOG.md
- feos-core/src/parameter/mod.rs
- feos-core/src/parameter/model_record.rs
- feos-core/src/python/cubic.rs
- feos-core/src/python/parameter.rs
- src/gc_pcsaft/eos/polar.rs
- src/pcsaft/parameters.rs
- src/uvtheory/python.rs
- tests/gc_pcsaft/binary.rs
While the core functionality, like the inclusion of binary segment records, were already part of FeOs, this PR fixes issues to make the feature actually usable.
> Group contribution method for binary interaction parameters

- CHANGELOG.md
- src/estimator/vapor_pressure.rs
Fixes #58 
Other properties are fine because we use iterators instead of a for-loop.
> Early return if vapor pressure data set is empty

- Cargo.toml
- benches/README.md
- benches/contributions.rs
times for calculating the first derivative for the following binary mixtures
||heptane|dme|acetylene|1-propanol|
|-|-|-|-|-|
|**hexane**|0.92μs|1.37μs|1.37μs|1.24μs|
|**acetone**|1.37μs|1.56μs|2.28μs|1.60μs|
|**co2**|1.37μs|2.29μs|1.58μs|1.69μs|
|**ethanol**|1.24μs|1.69μs|1.69μs|9.18μs|
Actually nice how symmetric everything is. Speaks for the reprocubility of the benchmarks.
> Add benchmark for different PC-SAFT contributions

- docs/theory/dft/derivatives.md
- docs/theory/dft/index.md
- feos-dft/CHANGELOG.md
- feos-dft/src/functional.rs
- feos-dft/src/functional_contribution.rs
- feos-dft/src/geometry.rs
- feos-dft/src/profile.rs
- feos-dft/src/python/profile.rs
- feos-dft/src/solver.rs
This PR introduces routines for the calculation of partial derivatives of density profiles with respect to chemical potential, pressure, and temperature. Since the calculation of the density profiles is implicit, a procedure similiar to that used in the Newton solver is used. The derivatives are calculated analytically using automatic differentiation. Therefore, the calculation is faster and more robust compared to approximating the profiles using numerical differentiation.
With the derivatives in place, enthalpies of adsorption should be readily available. In addition, the derivatives can be used to generate better initial values for the calculation of adsorption isotherms or surface tension diagrams.
While derivatives with respect to $p$ or $\mu$ are also available for heterosegmented …
> Partial derivatives of density profiles

- feos-core/CHANGELOG.md
- feos-core/src/phase_equilibria/bubble_dew.rs
Before this fix, the initial value for the composition of the opposing phase was ignored if no initial guess for the temperature or pressure was given. This behavior is confusing and should be changed. The value that was used to override the user-given initial values is remarkably robust for PC-SAFT but for other models (cubics...) this behavior is problematic.
> Fix unexpected behavior in the initialization of bubble and dew point calculations

- CHANGELOG.md
- Cargo.toml
- feos-core/CHANGELOG.md
- feos-core/Cargo.toml
- feos-dft/CHANGELOG.md
- feos-dft/Cargo.toml
This includes the necessary changes for the release of
- `feos-core` 0.4.1
- `feos-dft` 0.4.1
- `feos` 0.4.2
For the Rust crate itself, the release of `feos` is meaningless. However, the current system uses the same semver version for both the `feos` crate and Python package (which is good). Therefore, the new release is necessary.
> Release v0.4.2

- CHANGELOG.md
- src/gc_pcsaft/eos/parameter.rs
- src/gc_pcsaft/python/mod.rs
The $\varphi_i$ parameter in gc PC-SAFT corrects the model to obtain accurate pure component vapor pressures.
> Revive phi in hetero gc PC-SAFT

- CHANGELOG.md
- benches/contributions.rs
- benches/dual_numbers.rs
- feos-core/CHANGELOG.md
- feos-core/src/cubic.rs
- feos-core/src/parameter/mod.rs
- feos-core/src/python/parameter.rs
- feos-core/src/python/user_defined.rs
- src/association/mod.rs
- src/pcsaft/parameters.rs
- src/pets/parameters.rs
- src/pets/python.rs
- src/python/dft.rs
- src/python/eos.rs
- src/saftvrqmie/parameters.rs
- src/uvtheory/eos/mod.rs
- src/uvtheory/parameters.rs
- src/uvtheory/python.rs
Changes return types for constructor methods of `Parameter` to results. This is useful for parameters that contain assertions or have multiple, incompatible variants. Existing assertions/unwraps in implemented parameters have not been changed in this PR.
Since `Parameter::subset` is called on parameters that are usually created via the (now fallible) constructors, the method still returns the parameters without a results to keep the interfaces for property calculations clean. Added `panic` section to the doc strings.
> Make constructors in Parameter trait fallible

- feos-core/CHANGELOG.md
- feos-core/src/phase_equilibria/mod.rs
- feos-core/src/python/phase_equilibria.rs
Currently there is no way to create a `PhaseEquilibrium` object without calling any of the solvers. Some solvers (e.g., the tp flash), however, use a `PhaseEquilibrium` as initialization. Therefore the `new_npt` function can be used to create custom initial guesses. Currently the docstring informs the users that the result is not a phase equilibrium, but I would not be surprised if someone uses the function with the assumption that it is a (much faster and better converging) tp flash.
> Revive PhaseEquilibrium::new_npt in the public interface

- feos-core/CHANGELOG.md
- feos-core/src/phase_equilibria/bubble_dew.rs
This fixes the assignment of the liquid and vapor phases which helps tremendously for the calculation of supercritical phase diagrams.
The change with respect to the inital pressure is done because for high-pressure VLEs FeOs/PC-SAFT appear to find unphysical solutions at very low pressures. In this case, it is preferred to just not find any solution at all rather than the unphysical one.
> Fixes for the bubble and dew point calculations

- feos-core/CHANGELOG.md
- feos-core/src/cubic.rs
- feos-core/src/joback.rs
- feos-core/src/lib.rs
- feos-core/src/parameter/mod.rs
- feos-core/src/python/cubic.rs
- feos-core/src/python/joback.rs
- feos-core/src/python/parameter.rs
- src/pcsaft/parameters.rs
- src/pcsaft/python.rs
- src/pets/parameters.rs
- src/pets/python.rs
- src/saftvrqmie/parameters.rs
- src/saftvrqmie/python.rs
- src/uvtheory/parameters.rs
- src/uvtheory/python.rs
This PR comprises of two changes:
- The `binary_records` in `Parameter::from_records` is made optional. This removes some boilerplate from models that do not use binary interaction parameters at all (ideal gas models and pure component models). If the models have a GC method, they still need a custom struct for binary records to implement all necessary traits.
- A new constructor `Parameter::from_model_records` is added that internally creates the `PureRecord`s using defaults for molarweight and identifier, and does not use binary records. This is necessary, because at the moment, it is not possible to create `JobackParameters` from records in Python, since there is no appropriate `PureRecord` around.
> Optional binary records and new parameter constructor

- CHANGELOG.md
- src/eos.rs
- src/pcsaft/parameters.rs
- src/pcsaft/python.rs
- src/saftvrqmie/parameters.rs
- src/saftvrqmie/python.rs
...and some adjustments for parameter initialization from Python.
> added derive for EntropyScaling trait for SAFT-VRQ Mie for ResidualModel

- feos-core/src/joback.rs
The way binary interaction parameters are calculated later requires that this never fails rather than always fails.
> Fix FromSegmentsBinary for Joback

- feos-core/Cargo.toml
- feos-core/src/si/mod.rs
- feos-dft/CHANGELOG.md
- feos-dft/src/adsorption/mod.rs
- feos-dft/src/adsorption/pore.rs
- feos-dft/src/adsorption/pore2d.rs
- feos-dft/src/adsorption/pore3d.rs
- feos-dft/src/convolver/mod.rs
- feos-dft/src/convolver/periodic_convolver.rs
- feos-dft/src/geometry.rs
- feos-dft/src/interface/mod.rs
- feos-dft/src/interface/surface_tension_diagram.rs
- feos-dft/src/profile/mod.rs
- feos-dft/src/python/adsorption/pore.rs
- feos-dft/src/python/interface/mod.rs
- feos-dft/src/python/profile.rs
- src/python/dft.rs
- tests/gc_pcsaft/dft.rs
This is a MVSP for calculations of pores with non-orthorombic unit cells. Convolution integrals and integration is implemented, but to use non-orthorombic cells, the external potential has to be provided.
> Non orthogonal dft

- benches/dft_pore.rs
- examples/pcsaft_working_with_parameters.ipynb
- feos-core/CHANGELOG.md
- feos-core/src/joback.rs
- feos-core/src/parameter/mod.rs
- feos-core/src/parameter/model_record.rs
- parameters/pcsaft/README.md
- parameters/pcsaft/literature.bib
- parameters/pcsaft/rehner2023_hetero.json
- parameters/pcsaft/rehner2023_hetero_binary.json
- parameters/pcsaft/rehner2023_homo.json
- parameters/pcsaft/rehner2023_homo_binary.json
- parameters/pcsaft/sauer2014_smarts.json
- src/gc_pcsaft/eos/parameter.rs
- src/pcsaft/parameters.rs
> Update README for PC-SAFT parameters and add new binary record files

- CHANGELOG.md
- src/python/ideal_gas.rs
This adds `Identifier`, `IdentifierOption`, `PureRecord`, and `SegmentRecord` to `feos.ideal_gas`.
In the short term this allows to handle ideal gas parameters like other models. For the future, there remain 3 issues:
1. In Python, we have a `PureRecord` for every model, which can lead to confusing errors or the requirement to rename imports.
2. The `PureRecord` in `feos.ideal_gas` refers to Joback specifically, so if we add more models, the naming will be awkward.
3. It might be more clear if non-generic Python classes (`Identifier` and `IdentifierOption`) are exported only once.
> Add `PureRecord` and other Python classes to `feos.ideal_gas`

- feos-core/src/parameter/model_record.rs
- parameters/ideal_gas/poling2000.json
This is a temporary solution that allows writing json files for ideal gas models without molar weights but does not interfere with the other parameter files. In the future, `PureRecord` should be redesigned for Python to avoid having multiple classes of the same name.
> Allow missing molarweights in pure record json files

- CHANGELOG.md
- Cargo.toml
- feos-core/CHANGELOG.md
- feos-core/Cargo.toml
- feos-core/src/phase_equilibria/tp_flash.rs
In some cases, when the different solutions found by a stability analysis are right above the equality threshold, an almost trivial solution is used to initialize the tp flash for cases that could otherwise be solved very robustly.
MRE:
```python
from feos.si import *
from feos.pcsaft import *
from feos.eos import *
import numpy as np
pcsaft = PcSaftParameters.from_json(['cyclopentane', 'propylene'], '../input/esper2023.json')
eos = EquationOfState.pcsaft(pcsaft)
state = State(eos, 343.7964273175933*KELVIN, partial_density=np.array([78.77667866249813, 423.48238669680353])*MOL/METER**3)
state.tp_flash()
```
> Convergence improvement for tp_flash

- feos-core/CHANGELOG.md
- feos-core/src/state/mod.rs
```python
State(eos, 300*KELVIN, molefracs=np.array([1.5,3.5]), total_moles=10*MOL, pressure=BAR).moles
```
would previously evaluate to 
```
[15, 35] MOL
```
with this change the output is
```
[3, 7] MOL
```
which conforms with the total moles provided by the call to `State::new`. In any case, this is only an issue, if the molefracs do not add up to 1. A different approach would be to return an Error if this condition is not met, however, I'm not much in favor of adding an == 1.0 check due to the implications on floating point arithmetic.
> Enforce total_moles when providing molefracs that do not add up to 1

- docs/theory/eos/properties.md
- feos-core/CHANGELOG.md
- feos-core/src/python/state.rs
- feos-core/src/state/residual_properties.rs
Adds the calculation of Henry's law constants from an equation of state. Here, $H_{i,s}$ is defined in the way it would be observed, as
$H_{i,s}=\lim_{x_i\to 0}\frac{y_ip}{x_i}=p_s^\mathrm{sat}\frac{\varphi_i^{\infty,\mathrm{L}}}{\varphi_i^{\infty,\mathrm{V}}}$
The function treats all components with $x_i=0$ as solutes and returns only the Henry's law constants of those components.
In some sense, this would be an effective Henry's law constant that already contains the corrections for the non-ideality of the vapor phase and the pressure dependence of the liquid phase. Because this mainly serves as a tool to compare to experimental results or simplified modelling approaches, I don't see an issue.
```python
params = PcSaftParameters.from_json(["water", "nitrogen", "methanol", "carbon …
```
> Added Henry's law constant

- src/saftvrqmie/parameters.rs
- src/saftvrqmie/python.rs
Adds methods to get some useful properties in Python:
- de Boer parameter
- effective sigma and epsilon values
- prefactor `D` of FH correction
- hard sphere diameter
> Add property methods to `PySaftVRQMieParameters` object

- src/epcsaft/parameters.rs
added additional check if more than 0 permittivity points have been provided during creation of parameters
change only in `src/epcsaft/parameters.rs`
throws Error incompatible parameters if at least one of the components has 0 data points, but only if the permittivity record is some and not none.
> additional check of length of experimental permittivity data > 0

- .github/workflows/documentation.yml
Because it is incompatible with download-artifact version for documentation.
> fix version of upload-artifact Action

- feos-core/src/cubic.rs
- feos-core/src/equation_of_state/mod.rs
- feos-core/src/equation_of_state/residual.rs
- feos-core/src/lib.rs
- feos-core/src/python/phase_equilibria.rs
- feos-core/src/python/state.rs
- feos-core/src/python/user_defined.rs
- feos-core/src/state/properties.rs
- feos-core/src/state/residual_properties.rs
- feos-core/src/state/statevec.rs
- feos-derive/src/dft.rs
- feos-derive/src/residual.rs
- feos-dft/src/adsorption/pore.rs
- feos-dft/src/functional.rs
- src/eos.rs
- src/epcsaft/eos/mod.rs
- src/estimator/liquid_density.rs
- src/gc_pcsaft/dft/mod.rs
- src/gc_pcsaft/eos/mod.rs
- src/hard_sphere/dft.rs
- src/pcsaft/dft/mod.rs
- src/pcsaft/eos/mod.rs
- src/pets/dft/mod.rs
- src/pets/eos/mod.rs
- src/saftvrmie/eos/mod.rs
- src/saftvrqmie/dft/mod.rs
- src/saftvrqmie/eos/mod.rs
- src/uvtheory/eos/mod.rs
Analogous to `EntropyScaling`, implementing molar weights for models in Rust becomes optional again. Specific properties can thus only be evaluated if the trait is implemented.
IIRC, the last time around this lead to crashes due to panics within getters? The `StateVec` getters that require a molar weight and the `to_dict` methods will now check first if the given variant provides a molar weight.
> Reimplement Molarweight trait

- feos-dft/Cargo.toml
- feos-dft/src/adsorption/fea_potential.rs
Hello!
I saw that yours is a big project that uses the crate [`gauss-quad`](https://github.com/domidre/gauss-quad) that I am one of the maintainers of. We recently released version 0.2 that restructures the API. This PR updates `gauss-quad` as well as the two call sites to the new version so that you don't have to.
The main difference this PR introduces into your code is that it removes one computation of the nodes and weights and makes a previously hidden panic and allocation explicit.
As this is an unsolicited PR i understand completely if it is not something you are interested in.
> Update `gauss-quad` to 0.2

- Cargo.toml
- docs/theory/dft/ideal_gas.md
- docs/theory/dft/index.md
- feos-derive/src/dft.rs
- feos-dft/src/adsorption/mod.rs
- feos-dft/src/adsorption/pore.rs
- feos-dft/src/functional.rs
- feos-dft/src/functional_contribution.rs
- feos-dft/src/profile/mod.rs
- feos-dft/src/profile/properties.rs
- feos-dft/src/python/adsorption/pore.rs
- src/gc_pcsaft/dft/mod.rs
This adds the calculation of Henry coefficients and ideal gas enthalpies of adsorption, which can be evaluated without iterations straight from the external potential. Note that this is only possible for spherical or heterosegmented molecules, due to an approximation in the chain term in the homosegmented model.
> Ideal gas properties from DFT

- src/association/mod.rs
- src/pcsaft/parameters.rs
- src/pcsaft/python.rs
Thanks to @bbbursik for discovering the bug
in the existing code `#[serde(flatten)]` would invalidate the entire association record if `kappa_ab` and `epsilon_k_ab` were not both given. This is a problem for an induced association mixture, where one component has `nb!=0` but no association parameters, because those are only adjusted to pure component properties. The mixture would then not be able to describe the induced association, because the `nb` is essentially eliminated.
`kappa_ab` and `epsilon_k_ab` are optional, so `#[serde(flatten)]` will always be able to deserialize the `PcSaftAssocationRecord` struct. Induced association is calculated properly if binary association parameters are present. If there are no binary parameters for a certain combination of molecules, combining rules …
> Fix the handling of association records in combination with induced association in PC-SAFT

- feos-dft/src/adsorption/pore.rs
- feos-dft/src/adsorption/pore2d.rs
- feos-dft/src/adsorption/pore3d.rs
- feos-dft/src/convolver/mod.rs
- feos-dft/src/interface/mod.rs
- feos-dft/src/profile/mod.rs
- feos-dft/src/profile/properties.rs
- feos-dft/src/solvation/pair_correlation.rs
- feos-dft/src/solvation/solvation_profile.rs
Previously, a default of `None` was used, when derivatives were calculated.
> Always use the same lanczos sigma factor within one DFT profile

- py-feos/src/eos/epcsaft.rs
- py-feos/src/eos/pcsaft.rs
- py-feos/src/eos/pets.rs
- py-feos/src/eos/saftvrmie.rs
- py-feos/src/eos/saftvrqmie.rs
- py-feos/src/eos/uvtheory.rs
They are not part of the Python module right now anyways and it is difficult to conceive of an appropriate place in the module structure.
> Replace the model-specific enums in Python with Strings

- crates/feos/src/pcsaft/eos/polar.rs
Confirms the bug in #292. Should we just update the value in the test that checks against a hardcoded helmholtz energy? It's impossible to backtrack where that value is from, but having it is a good check for future changes to the code.
> Add tests that check the polar contributions with respect to reordering components
